version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=500
    ports:
      - 10002:5432
  db-test:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: postgres-test
    command: --c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=500
    ports:
      - 10003:5432