version: "3.9"
services:
  db-book:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres-book
      POSTGRES_PASSWORD: postgres-page
    ports:
      - 10002:5432
  db-sauce:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres-sauce
      POSTGRES_PASSWORD: postgres-cholula
    ports:
      - 10003:5432